- name: Continuous Download and Continuous Build
  hosts: devserver
  tasks:
    - name: Download dev code from github
      git:
        repo: https://github.com/intelliqittrainings/maven.git
        dest: dev-git
    - name: Create an artifact using maven
      shell: cd dev-git;mvn package
