---
- name: Implementing tags
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: tree_installation
    - name: User creation
      user: 
        name: Radha
        password: Bathula
      tags: user_creation
    - name: Copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp

...         
